version: '3'
services:
  app:
    build: ./
    volumes:
      - ./:/app
      - /app/node_modules
      - ../puppeteer-duellinks-data:/app/data
    container_name: puppeteer-duellinks-prod
    env_file:
      - .env.production